### ISSUE TITLE
Doubt Equation 12 (and Figure 4 vs Figure 2)

### ISSUE THREAD

**Issue by cgr71ii** [mt-upc/transformer-contributions-nmt#4]
Hi!

First of all, thank you for your work and for releasing the resources. I really enjoyed reading the paper :)

Looking at Figure 4, I noticed that only the encoder output was connected to the cross-attention module, instead of both the encoder and decoder self-attention module outputs. Then I observed the same behaviour described in Equation 12: the cross-attention module processes only the encoder output and it is summed to the decoder self-attention module. Please correct me if I'm wrong (there are many reformulations of equations in the XAI field as far as I've read), but the encoder-decoder transformer processes both the encoder and decoder outputs in the cross-attention module. In [Attention Is All You Need](https://proceedings.neurips.cc/paper_files/paper/2017/file/3f5ee243547dee91fbd053c1c4a845aa-Paper.pdf) we can read this; in particular, that the Q inputs come from the previous self-attention decoder module, and that K and V come from the encoder output:

> In "encoder-decoder attention" layers, the queries come from the previous decoder layer, and the memory keys and values come from the output of the encoder. This allows every position in the decoder to attend over all positions in the input sequence. This mimics the typical encoder-decoder attention mechanisms in sequence-to-sequence models such as [31, 2, 8].

I've checked that this is how M2M works in the Transformers library, in case a new behaviour for the transformer model has been introduced in the literature since it was first presented, but apparently this is not the case. Regarding the cross-attention in the M2M model, we can observe the same behaviour that was first introduced in the transformer paper in the following lines of the `M2M100DecoderLayer` class (that Q is obtained from the decoder and K and V from the encoder):

https://github.com/huggingface/transformers/blob/a06a0d12636756352494b99b5b264ac9955bc735/src/transformers/models/m2m_100/modeling_m2m_100.py#L737:L755

Then I wonder if I have missed something in Figure 4 or in Equation 12? In fact, the connection I'm talking about (Q coming from the decoder, K and V coming from the encoder, for the cross-attention module) is partially shown in Figure 2 of your paper, similar to how the encoder-decoder transformer is shown in the Attention Is All You Need paper. My particular problem is that I cannot see how in Equation 12 the encoder and decoder values are mixed in the *cross*-attention module.

Thanks!

**Comment by javiferran** [comment]
Hi Cristian!

Thanks for checking our work!
As you say, the cross-attention processes both the encoder outputs and the previous decoder self-attention output. The previous self-attention outputs are only used to compute the queries (Q), and subsequently the attention weights. While the encoder outputs are transformed into the keys (K) and values (V). This means that the output of the cross-attention -green arrow on top of $MHA^c_t$ in Figure 2- only contains information from the encoder outputs, since all information comes through the values. The (cross)attention weights just 'prioritize' some values over others. Since we are only illustrating information flow, we don't show the arrow coming from the self-attention.
Regarding Equation 12, note that $F^c_t(e_j) = \sum_h^H W_O^h\alpha^h_{i,j}W^h_V e_j$. That is, the output of the self-attention is implicitly present in the (cross)attention weights $\alpha$.

Please let us know if you would like any additional clarification!

**Comment by cgr71ii** [comment]
Ok, ok, I see the point of showing the flow of information in Figure 2! I also now clearly see that the information coming from the decoder appears in Equation 12.

Thanks for your time and clarifications, Javier :)
